apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.2/manifests/ha/install.yaml

patches:
- path: patches/argocd-server-deployment-kustomize-spec-patch.yaml
  target:
    kind: Deployment
    name: argocd-server
