helmDefaults:
  atomic: false
  wait: true
  timeout: 300

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    chart: argo/argo-cd
    namespace: argocd
    createNamespace: true
