apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
bases:
- ../../base/

transformers:
- transformers/metadata-labels.yaml

patchesStrategicMerge:
- patches/argocd-rbac-cm-kustomize-data-patch.yaml

secretGenerator:
- name: cluster-shared-eu-we1
  literals:
  - name=local
  - config='{"tlsClientConfig":{"insecure":false}}'
  - server=https://kubernetes.default.svc
