apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Update this section with your Git repository information
  source:
    # Option 1: Public GitHub/GitLab repository
    repoURL: https://github.com/YOUR_USERNAME/YOUR_REPO.git
    
    # Option 2: In-cluster Gitea (if using setup-gitea.sh)
    # repoURL: http://gitea.gitea.svc.cluster.local:3000/YOUR_USERNAME/argocd-config.git
    
    targetRevision: HEAD  # or specify a branch like "main" or "master"
    path: helm-charts/guestbook
    
    helm:
      releaseName: guestbook
      valueFiles:
        - values.yaml
      
      # Optional: Override values
      # values: |
      #   replicaCount: 2
      #   service:
      #     type: LoadBalancer
  
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  
  syncPolicy:
    automated:
      prune: true        # Remove resources when they're removed from Git
      selfHeal: true     # Force sync when cluster state differs from Git
      allowEmpty: false  # Don't sync if source is empty
    
    syncOptions:
      - CreateNamespace=true              # Create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground # Wait for resources to be deleted
      - PruneLast=true                    # Prune resources last
      - ServerSideApply=true              # Use server-side apply
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica count if using HPA
