{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}-redis
  labels:
    app: guestbook
    component: redis
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.master.service.type }}
  ports:
  - port: {{ .Values.redis.master.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app: guestbook
    component: redis
{{- end }}
